title: Haoqing Xu's Homepage
page-top-title: Haoqing Xu
top-section-bg-text: Biomedical Science
home-subtitle: Haoqing Xu&ensp;|&ensp;许昊清
copyright-text: '&copy; Haoqing Xu 2026. All Rights Reserved.'
